apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless-ngx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts 
    repoURL: "git@github.com:Pieter-Visscher/kubernetes-argo.git"
    targetRevision: "*"
  destination:
    server: https://kubernetes.default.svc
    namespace: paperless-ngx
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
