apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-2replica
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "2"
  dataLocality: "best-effort"
  fsType: "ext4"
allowVolumeExpansion: true
reclaimPolicy: Delete
